[package]
name = "account-transactions"
version = "1.0.0"
edition = "2021"
authors = ["Kamil Łasek"]

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
clap = "2.33.3"
anyhow = "1.0.38"
thiserror = "1.0.24"
tokio = { version = "1.14.1", features = ["full"] }
